config/routes.rb
VideoStore::Application.routes.draw do
  resources :categories do
      resources :movies
  end

  resources :users
  
  resource :session

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :movies
  
  #Validations
  validates :name, :presence => true
  validates :e_mail, :presence => true
  validates :e_mail, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }
  validates :e_mail, :uniqueness => true 
  validates :phone_number, :presence => true
  validates :address, :presence => true
  validates :role, :presence => true
  validates :password, :presence => true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def authenticate
    if(session[:user_id] == nil)
      @current_user = session[:user_id]
      redirect_to new_session_path, :notice => "Please log in to continue" 
      return false
    else
      @current_user = User.find(session[:user_id])
      return true
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate
  # GET /categories
  # GET /categories.json
  def index
    @user = session[:user_id]
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :authenticate
  before_filter(:get_category)
  # GET /movies
  # GET /movies.json
  def index
    @movies = @category.movies.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = @category.movies.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = @category.movies.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = @category.movies.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = @category.movies.new(params[:movie])

    respond_to do |format|
      if @movie.save
        flash[:notice] = 'Movie was successfully created.'
        format.html { redirect_to(category_movie_url(@category, @movie)) }#, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = @category.movies.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        flash[:notice] = 'Movie was successfully updated.'
        format.html { redirect_to(category_movie_url(@category, @movie)) }#, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = @category.movies.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to(category_movies_url(@category)) }
      format.json { head :no_content }
    end
  end
  
  def get_category
    @category = Category.find(params[:category_id])
  end
  
  def rent
    @movie = @category.movies.find(params[:id])
    @movie.users << @current_user
    @movie.update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    user = User.first(:conditions => ["e_mail = ? and password = ?", params[:e_mail], params[:password]]) 
    if(user != nil)
      session[:user_id] = user.id
      redirect_to categories_path, :notice => "Loged in succesfully"
    else
      flash.now[:alert] = "Invalid login/password combination"
      render :action => 'new'
    end 
  end
  
  def destroy
    reset_session
    redirect_to categories_path, :notice => "You succesfully logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h3>Welcome back!:
	<%= @current_user.name %> 
</h3>

<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= link_to 'Show', category %></td>
    <% if(@current_user.role == "Administrator") %>
    	<td><%= link_to 'Edit', edit_category_path(category) %></td>
    	<td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if(@current_user.role == "Administrator") %>
	<%= link_to 'New Category', new_category_path %> |
<% end %>
<%= link_to 'Logout', session_path, :method => :delete %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>

<p>
	<b>Listing movies:</b><br /><br />
	<% @category.movies.each do |movie| %>
		<%= "Title: " + movie.title %>
		<td><%= link_to 'Show', category_movie_path(@category, movie) %></td>
		<% if(@current_user.role == "Administrator") %>
			<td><%= link_to 'Edit', edit_category_movie_path(@category, movie) %></td>
		<% end %>
		<br />
	<% end %>
</p>

<% if(@current_user.role == "Administrator") %>
	<%= link_to 'Edit', edit_category_path(@category) %> |
<% end %>
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for([@category, @movie]) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :film_director %><br />
    <%= f.text_field :film_director %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :cast %><br />
    <%= f.text_area :cast %>
  </div>
  <div class="field">
    <%= f.label :copy_number %><br />
    <%= f.number_field :copy_number %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', category_movie_path(@category, @movie) %> |
<%= link_to 'Back', category_movies_path(@category) %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Film director</th>
    <th>Description</th>
    <th>Cast</th>
    <th>Copy number</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.title %></td>
    <td><%= movie.film_director %></td>
    <td><%= movie.description %></td>
    <td><%= movie.cast %></td>
    <td><%= movie.copy_number %></td>
    <td><%= movie.category %></td>
    <td><%= link_to 'Show', category_movie_path(@category, movie) %></td>
    <td><%= link_to 'Edit', edit_category_movie_path(@category, movie) %></td>
    <td><%= link_to 'Destroy', category_movie_path(@category, movie), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_category_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', category_movies_path(@category) %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @movie.title %>
</p>

<p>
  <b>Film director:</b>
  <%= @movie.film_director %>
</p>

<p>
  <b>Description:</b>
  <%= @movie.description %>
</p>

<p>
  <b>Cast:</b>
  <%= @movie.cast %>
</p>

<p>
  <b>Copy number:</b>
  <%= @movie.copy_number %>
</p>

<p>
  <b>Category:</b>
  <%= @movie.category.name %>
</p>


<% if(@current_user.role == "Administrator") %>
	<%= link_to 'Edit', edit_category_movie_path(@category, @movie) %> |
<% end %>
<%= link_to 'Back', category_path(@category) %><br /><br />

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :e_mail %><br />
    <%= f.text_field :e_mail %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>E mail</th>
    <th>Phone number</th>
    <th>Address</th>
    <th>Role</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.e_mail %></td>
    <td><%= user.phone_number %></td>
    <td><%= user.address %></td>
    <td><%= user.role %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>E mail:</b>
  <%= @user.e_mail %>
</p>

<p>
  <b>Phone number:</b>
  <%= @user.phone_number %>
</p>

<p>
  <b>Address:</b>
  <%= @user.address %>
</p>

<p>
  <b>Role:</b>
  <%= @user.role %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>